FORMAT: 1A
HOST: https://jsonplaceholder.typicode.com/

# APITEST

Todo is a simple API allowing consumers to view todos and complete update.

## Todos Collection [/todos]

### List All Todos [GET]

+ Response 200 (application/json)

        [
            {
              "userId": 1,
              "id": 1,
              "title": "first todo",
               "completed": false
            },
            {
               "userId": 1,
               "id": 2,
               "title": "try",
               "completed": true
            }
        ]

### Create a New Todo [POST]

You may create your own todo using this action. It takes a JSON
object containing a todo and a complete status.

+ Request (application/json)

        {
               "userId": 2,
               "id": 3,
               "title": "New Todo",
               "completed": false
        }

+ Response 201 (application/json)

    + Headers

            Location: /todo/2

    + Body

            {
               "userId": 2,
               "id": 3,
               "title": "New Todo",
               "completed": false
            }